### ISSUE TITLE
Packages out of date

### ISSUE THREAD

**Issue by IgniparousTempest** [exponent/nativebase-example#2]
Could all the packages be updated to the latest compatible versions?

**Comment by IgniparousTempest** [comment]
I have created a pull request, see [pull/3](https://github.com/expo/nativebase-example/pull/3).

**Comment by brentvatne** [comment]
thanks for doing this -- we're not going to maintain this repository so I changed the README to just point to the NativeBase README: https://github.com/expo/nativebase-example/blob/master/README.md
